FROM node:20-alpine as build
WORKDIR /app
COPY package.json ./
RUN npm i --verbose
COPY . .
COPY deploy/.prod.env /app/.env
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/deploy/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]